#!/bin/bash
cd() {
	if [ -z "$1" ]; then
		builtin cd
	else
		builtin cd "$1"
		num_elements=$(exa -al --color=always --group-directories-first | wc -l)
		if [ "$num_elements" -le 25 ]; then
			exa -al --color=always --group-directories-first --icons
		fi
	fi
}

lt() {
	depth=${1:-2}
	exa -aT -L $depth --color=always --group-directories-first --icons
}

function path_cleanup() {
	if [ -n "$PATH" ]; then
		old_PATH=$PATH:
		PATH=
		while [ -n "$old_PATH" ]; do
			x=${old_PATH%%:*}
			case $PATH: in
			*:"$x":*) ;;
			*) PATH=$PATH:$x ;;
			esac
			old_PATH=${old_PATH#*:}
		done
		PATH=${PATH#:}
		unset old_PATH x
	fi
}

Bright() {
    if [ -z "$1" ]; then
        echo "Usage: set_brightness <value>"
        return 1
    fi

    BRIGHTNESS_PATH="/sys/class/backlight/intel_backlight/brightness"

    MAX_BRIGHTNESS=$(cat /sys/class/backlight/intel_backlight/max_brightness)
    
    if [ "$1" -ge 0 ] && [ "$1" -le "$MAX_BRIGHTNESS" ]; then
        echo "$1" | sudo tee "$BRIGHTNESS_PATH" > /dev/null
        echo "Brightness set to $1 (Max: $MAX_BRIGHTNESS)"
    else
        echo "Error: Brightness value must be between 0 and $MAX_BRIGHTNESS"
        return 1
    fi
}

