#!/bin/sh

# resources 
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"
wallpaper="/usr/share/Wallpapers/redSea.jpg"
log_file="/var/log/xinitrc_errors.log"

# Merge in defaults and keymaps
[ -f "$sysresources" ] && xrdb -merge "$sysresources"
[ -f "$sysmodmap" ] && xmodmap "$sysmodmap"

# system-wide scripts
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "$f" ] && . "$f"
    done
    unset f
xbindkeys -f /etc/X11/xinit/xbindkeysrc &
fi

# no x bell
xset b off
xset r rate 300 50

# NumLock
numlockx on || echo "Error: numlockx on from xinitrc" >> $log_file

# wallpaper
wall_dir=$(dirname "$wallpaper")
[ -d "$wall_dir" ] && feh --bg-scale --randomize "$wall_dir"/* || echo "Error: Unable to set wallpaper from $wall_dir" >> $log_file

# xmonad
if [ -x "$(command -v xmonad)" ]; then
   exec /home/devid/.xmonad/xmonad-x86_64-linux
#  exec xmonad
else
    echo "Error: Unable to launch xmonad from xinitrc" >> $log_file
    exit 1
fi

