#!/usr/bin/env bash
#
# Script name: dm-wiki
# Description: Search an offline copy of the Arch Wiki.
# Dependencies: dmenu, arch-wiki-docs
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               marvhus

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null

source_dmscripts_configs

if configs_are_different; then
    echo "$(date): configs are different" >>"$DM_CONFIG_DIFF_LOGFILE"
    sleep 1
fi

wikidir="/usr/share/doc/arch-wiki/html/"
lang=""

languages() {
    langs="$(find ${wikidir} -maxdepth 1 -type d -not -path "${wikidir}")"
    choice=$(printf '%s\n' "${langs[@]}" \
        | sed 's/.*\///' \
        | sort -g \
        | ${MENU} 'Language: ') || exit 1

    if [ "$choice" ]; then
        lang=$(printf '%s' "${choice}/")
        echo "$lang"
        wikipages
    else
        echo "Program terminated." && exit 0
    fi
}

wikipages() {
    wikidocs="$(find ${wikidir}"${lang}" -iname "*.html")"
    choice=$(printf '%s\n' "${wikidocs[@]}" \
        | cut -d '/' -f8- \
        | sed -e 's/_/ /g' -e 's/.html//g' \
        | sort -g \
        | ${MENU} 'Arch Wiki Docs: ') || exit 1

    if [ "$choice" ]; then
        article=$(printf '%s\n' "${wikidir}${lang}${choice}.html" | sed 's/ /_/g')
        ${DMBROWSER} "$article"
    else
        echo "Program terminated." && exit 0
    fi
}

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && languages
