#!/bin/bash

MOUNT_POINT="/home/devid/.password-store"
CRYPT_DIR="/home/devid/.encrypted-store"

if mountpoint -q "$MOUNT_POINT"; then
    echo "Password store already mounted."
    exit 0
fi

# Opens a terminal for stdin passwd (dmenu req)
alacritty -e bash -c "gocryptfs \"$CRYPT_DIR\" \"$MOUNT_POINT\""
