#!/bin/bash
STATE="/tmp/update-count"

    pacman_count=$(checkupdates 2>/dev/null | wc -l)
    aur_count=$(yay -Qua 2>/dev/null | wc -l)

    echo "$pacman_count.$aur_count" > "$STATE"

cat "$STATE"

