#!/bin/sh
xrandr \
  --output HDMI-1 --mode 1920x1080 --scale 1.3333x1.3333 --panning 2560x1440+0+0 --pos 0x0 --rotate normal \
  --output eDP-1  --primary --mode 2560x1600 --scale 1x1       --pos 0x1440       --rotate normal --rate 240  \
  --output DP-1 --off --output DP-2 --off --output DP-3 --off \
  --output DP-4 --off --output DP-5 --off --output DP-6 --off

