#!/bin/sh
xrandr \
  --fb 2688x3112 \
  --output HDMI-1 --mode 1920x1080 --transform 1.4,0,0,0,1.4,0,0,0,1 --panning 2688x1512+0+0 --pos 0x0 --rotate normal \
  --output eDP-1  --primary --mode 2560x1600 --scale 1x1 --pos 0x1512 --rotate normal --rate 240 \
  --output DP-1 --off --output DP-2 --off --output DP-3 --off \
  --output DP-4 --off --output DP-5 --off --output DP-6 --off
